# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Data Science @ Sac State
description: > # this means to ignore newlines until "baseurl:"
  SacState's official Data Science club

# the base hostname & protocol for your site
url: "http://www.piplotter.com"

# the subpath of your site, e.g. /blog
baseurl: "" 
github_username:  datascience-sacstate
    
# Build settings
markdown: kramdown
permalink: /:categories/:title/
